name: dolfinx_complex
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.*
  - dolfinx_mpc=0.6.1
  - fenics-dolfinx=0.6.0
  - jupyter
  - matplotlib
  - petsc=*=*complex*
  - pyvista
  - slepc=*=*complex*
